services:
  web:
    build: .
    working_dir: /app
    volumes:
      - ./app:/app
      - ./alembic.ini:/app/alembic.ini
    ports:
      - "8000:8000"
    command: >
      sh -c "PYTHONPATH=/app alembic upgrade head && PYTHONPATH=/app uvicorn main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env