"""create historical_figures table

Revision ID: 64493378c06b
Revises: 
Create Date: 2025-07-11 14:18:51.659269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64493378c06b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'historical_figures',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('name', sa.String, unique=True, index=True, nullable=False),
        sa.Column('description', sa.String, nullable=False),
        sa.Column('picture_url', sa.String, nullable=True)
    )
    # Insert initial data
    historical_figures = sa.table('historical_figures',
        sa.column('name', sa.String),
        sa.column('description', sa.String),
        sa.column('picture_url', sa.String)
    )
    op.bulk_insert(historical_figures, [
        {"name": "King Arthur", "description": "Legendary British leader.", "picture_url": "https://upload.wikimedia.org/wikipedia/commons/5/5d/King_Arthur_-_Howard_Pyle.jpg"},
        {"name": "Joan of Arc", "description": "French heroine and saint.", "picture_url": "https://upload.wikimedia.org/wikipedia/commons/1/19/Joan_of_Arc_miniature_graded.jpg"}
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historical_figures')
    # ### end Alembic commands ###
